# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "1c0029b6650e32daac8653bcbe8a6334"
name = "banner-for-country"
handle = "banner-for-country"
application_url = "https://anniversary-precise-constitutes-encouraged.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "checkout-extension-big.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://anniversary-precise-constitutes-encouraged.trycloudflare.com/auth/callback",
  "https://anniversary-precise-constitutes-encouraged.trycloudflare.com/auth/shopify/callback",
  "https://anniversary-precise-constitutes-encouraged.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
